titanSideCars:
  envoy:
    logFolderPath: /tests/logs
    useDynamicConfiguration: true
    clusters:
      local-myapp:
        type: STRICT_DNS
        address: myapp
  ratelimit:
    enabled: true
    address: ratelimit
    type: STRICT_DNS
    
  validation:
    enabled: true
    ## uncomment following lines to change to use different images
    environment:
      containers:
        proxy:
          image: sbo-sps-docker-release-local.usw1.packages.broadcom.com/sps-images/envoy:1.18.3-redhat-fips-titan-proxy-wasm-bundle.20
        ratelimit: 
          image: sbo-sps-docker-release-local.usw1.packages.broadcom.com/sps-images/ratelimit:v1.4.0.3-redhat-fips-master.1
