aliases:
  canaryRoutingHeaderName:  &canaryRoutingHeaderName x-epmp-route-by-release

canary:
  enabled: true
  labelRegex: "^[A-Za-z0-9._-]+-[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9]$" 
  labelIndex: -10
  routeHeader: *canaryRoutingHeaderName

global:
  titanSideCars:
    canary:
      routeHeaderName: *canaryRoutingHeaderName
