domain: myapp

descriptors:
- key: header_match
  value: oidc_login_497cb6811f2fc123
  descriptors:
  - key: key_cf236a0e2b8123dc
    rate_limit:
      unit: hour
      requests_per_unit: 1000
- key: header_match
  value: authentication_a69bec24fe2dade6
  descriptors:
  - key: key_90b93ca80aab08ef
    rate_limit:
      unit: hour
      requests_per_unit: 1000
- key: header_match
  value: post_oauth2_token_symantec_domain_c4904466c6d20791
  descriptors:
  - key: key_2552c29574ad90e2
    rate_limit:
      unit: hour
      requests_per_unit: 1000
- key: header_match
  value: post_oauth2_token_a08fc479a3144a02
  descriptors:
  - key: key_50e931904607af12
    rate_limit:
      unit: hour
      requests_per_unit: 1000
- key: header_match
  value: token_validation_ver_1_f2266b6f57507497
  descriptors:
  - key: key_30288c0acb8c407d
    rate_limit:
      unit: hour
      requests_per_unit: 1000

