{{- define "titan-mesh-helm-lib-chart.configs.envoy.dmc" }}
  {{- $titanSideCars := .titanSideCars }}
  {{- $appName := .appName }}
  {{- $releaseNamespace := .releaseNamespace }}
  {{- $chartName := .chartName }}
  {{- $envoy := $titanSideCars.envoy }}
  {{- $supportPathConfigSource := $envoy.supportPathConfigSource | default false }}
  {{- $envoyAdminPort := $envoy.adminPort | default "10000"  }}
  {{- $envoyStatsPort := $envoy.statsPort | default "8126"  }}
  {{- $envoyStatsFlushInterval := $envoy.statsFlushInterval | default "30s"  }}
  {{- $clusters := $envoy.clusters  }}
  {{- if not $clusters }}
    {{- fail ".Values.titanSideCars.envoy.clusters is required" }}
  {{- end }}
  {{- if not (index $clusters "local-myapp") }}
    {{- fail ".Values.titanSideCars.envoy.clusters.local-myapp is required" }}
  {{- end }}
  {{- $ingress := $titanSideCars.ingress }}
  {{- $egress := $titanSideCars.egress }}
  {{- $ingressEnabled := ternary $ingress.enabled true (hasKey $ingress "enabled") -}}
  {{- $egressEnabled := ternary $egress.enabled true (hasKey $egress "enabled") -}}
  {{- if or $ingressEnabled $egressEnabled }}
    {{- $envoyConfigFolder := $envoy.configFolder | default "/envoy/config" }}
    {{- $cdsFolder := $envoy.cdsFolderPath | default (printf "%s/cds" (trimSuffix "/" $envoyConfigFolder)) -}}
    {{- $ldsFolder := $envoy.ldsFolderPath | default (printf "%s/lds" (trimSuffix "/" $envoyConfigFolder)) -}}
    {{- $loadDynamicConfigurationFromGcs := $envoy.loadDynamicConfigurationFromGcs -}}
    {{- $loadDynamicConfigurationFromGcsEnabled := ternary $loadDynamicConfigurationFromGcs.enabled false (hasKey $loadDynamicConfigurationFromGcs "enabled") -}}
envoy.yaml: |
  node:
    cluster: {{ $appName }}
    id: {{ printf "%s-id" $appName }}

  dynamic_resources:
      {{- if $supportPathConfigSource }}
    cds_config:
      path_config_source: 
        path: {{ printf "%s/cds.yaml" (trimSuffix "/" $cdsFolder) }}
        {{- if not $loadDynamicConfigurationFromGcsEnabled }}
        watched_directory: 
          path: {{ printf "%s" (trimSuffix "/" $cdsFolder) }}
        {{- end }}
    lds_config:
      path_config_source:
        path: {{ printf "%s/lds.yaml" (trimSuffix "/" $ldsFolder) }}
        {{- if not $loadDynamicConfigurationFromGcsEnabled }}
        watched_directory: 
          path: {{ printf "%s" (trimSuffix "/" $ldsFolder) }}
        {{- end }}
      {{- else }}
    cds_config:
      path: {{ printf "%s/cds.yaml" (trimSuffix "/" $cdsFolder) }}
    lds_config:
      path: {{ printf "%s/lds.yaml" (trimSuffix "/" $ldsFolder) }}
      {{- end }}
  admin:
    access_log_path: /dev/stdout
    address:
      socket_address:
        address: 0.0.0.0
        port_value:  {{ $envoyAdminPort }}
  stats_flush_interval: {{ $envoyStatsFlushInterval }}
  stats_sinks:
    - name: envoy.stat_sinks.statsd
      typed_config:
        "@type": type.googleapis.com/envoy.config.metrics.v3.StatsdSink
        address:
          socket_address:
            address: 127.0.0.1
            port_value: {{ $envoyStatsPort }}
            protocol: UDP

  {{- end }}
{{- end }}
