{{- define "titan-mesh-helm-lib-chart.configs.envoy" }}
  {{- $titanSideCars := .titanSideCars }}
  {{- $appName := .appName }}
  {{- $releaseNamespace := .releaseNamespace }}
  {{- $chartName := .chartName }}
  {{- $envoy := $titanSideCars.envoy }}
  {{- $supportPathConfigSource := $envoy.supportPathConfigSource | default false }}
  {{- $envoyAdminPort := $envoy.adminPort | default "10000"  }}
  {{- $envoyStatsPort := $envoy.statsPort | default "8126"  }}
  {{- $envoyStatsFlushInterval := $envoy.statsFlushInterval | default "30s"  }}
  {{- $clusters := $envoy.clusters  }}
  {{- if not $clusters }}
    {{- fail ".Values.titanSideCars.envoy.clusters is required" }}
  {{- end }}
  {{- if not (index $clusters "local-myapp") }}
    {{- fail ".Values.titanSideCars.envoy.clusters.local-myapp is required" }}
  {{- end }}
  {{- $ingress := $titanSideCars.ingress  }}
  {{- $egress := $titanSideCars.egress  }}
  {{- $ingressEnabled := ternary $ingress.enabled true (hasKey $ingress "enabled") -}}
  {{- $egressEnabled := ternary $egress.enabled true (hasKey $egress "enabled") -}}
  {{- if or $ingressEnabled $egressEnabled }}
envoy.yaml: |
  admin:
    access_log_path: /dev/stdout
    address:
      socket_address:
        address: 0.0.0.0
        port_value:  {{ $envoyAdminPort }}
  stats_flush_interval: {{ $envoyStatsFlushInterval }}
  stats_sinks:
    - name: envoy.stat_sinks.statsd
      typed_config:
        "@type": type.googleapis.com/envoy.config.metrics.v3.StatsdSink
        address:
          socket_address:
            address: 127.0.0.1
            port_value: {{ $envoyStatsPort }}
            protocol: UDP
    {{- if $envoy.statsConfigRaw }}
  stats_config:
      {{- $envoy.statsConfigRaw | toYaml | nindent 2 }}
    {{- end }}
  static_resources:
    clusters:
    {{- include "titan-mesh-helm-lib-chart.envoy.clusters" (dict "titanSideCars" $titanSideCars "releaseNamespace" $releaseNamespace "chartName" $chartName "useDynamicConfiguration" false "appName" $appName) }}
    listeners:
    {{- include "titan-mesh-helm-lib-chart.envoy.listeners" (dict "titanSideCars" $titanSideCars "releaseNamespace" $releaseNamespace "chartName" $chartName "useDynamicConfiguration" false "appName" $appName) }}

  {{- end }}
{{- end }}
