{{- define "titan-mesh-helm-lib-chart.configs.envoy.cds" }}
  {{- $titanSideCars := .titanSideCars }}
  {{- $appName := .appName }}
  {{- $releaseNamespace := .releaseNamespace }}
  {{- $chartName := .chartName }}
  {{- $ingress := $titanSideCars.ingress }}
  {{- $egress := $titanSideCars.egress }}
  {{- $ingressEnabled := ternary $ingress.enabled true (hasKey $ingress "enabled") -}}
  {{- $egressEnabled := ternary $egress.enabled true (hasKey $egress "enabled") -}}
  {{- if or $ingressEnabled $egressEnabled }}
cds.yaml: |
  resources:
      {{- include "titan-mesh-helm-lib-chart.envoy.clusters" (dict "titanSideCars" $titanSideCars "releaseNamespace" $releaseNamespace "chartName" $chartName "useDynamicConfiguration" true "appName" $appName) }}

  {{- end }}
{{- end }}
