{{- define "titan-mesh-helm-lib-chart.configs.opa-policy-tokenspec" }}
  {{- $global := $.Values.global -}}
  {{- $titanSideCars := mergeOverwrite (deepCopy ($global.titanSideCars | default dict)) ($.Values.titanSideCars | default dict) -}}
  {{- $opa := $titanSideCars.opa -}}
policy-tokenspec.rego: |
  {{- $customPolicies := $opa.customPolicies }}
  {{- if $customPolicies.tokenSpec }}
  {{- $customPolicies.tokenSpec | nindent 2 }}
  {{- else }}
  # Default Spec - Standard JWT Bearer Token
  package authz.token
  import input.attributes.request.http as request

  default authz_header = ""
  authz_header = trim_space(request.headers.authorization)
  token = claims {
    startswith(authz_header, "Bearer ")
    [_, encoded] := regex.split("[ ]+", authz_header)
    [_, claims, _] := io.jwt.decode(encoded) 
  }
  {{- end }}
{{- end }}