{{- define "titan-mesh-helm-lib-chart.configs.ratelimit" }}
  {{- $global := $.Values.global -}}
  {{- $titanSideCars := mergeOverwrite (deepCopy ($global.titanSideCars | default dict)) ($.Values.titanSideCars | default dict) -}}
  {{- $ratelimitEnabled := eq (include "static.titan-mesh-helm-lib-chart.ratelimitEnabled" $titanSideCars) "true" -}}
  {{- $appName := include "titan-mesh-helm-lib-chart.app-name" . -}}
  {{- $ingress := $titanSideCars.ingress }}
  {{- $envoy := $titanSideCars.envoy }}
  {{- $ratelimit := $envoy.ratelimit }}
  {{- $clusters := $envoy.clusters }}
  {{- $localApp := index $clusters "local-myapp" }}
  {{- $hasRatelimit := false }}

  {{- $gateway := $localApp.gateway }}
  {{- $gatewayEnable := $gateway.enabled }}
  {{- $routes := list }}
  {{- if $gatewayEnable }}
    {{- range $cn, $cv := $clusters }}
      {{- if and (ne $cn "local-myapp") (ne $cn "remote-myapp") }}
        {{- $ratelimitRoutes := $cv.routes }} 
        {{- if $cv.ratelimit }}
          {{- if $cv.ratelimit.routes }}
            {{- $ratelimitRoutes = $cv.ratelimit.routes }} 
          {{- end }}
        {{- end }}
        {{- range $ratelimitRoutes }}
          {{- $newcluster := dict "cluster" $cn }}
          {{- $routes = append $routes (dict "match" .match "route" $newcluster "ratelimit" .ratelimit) }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- else }}
    {{- $routes = $ingress.routes }}
    {{- if and $ingress (not $routes) }}
      {{- if ternary $ingress.enabled true (hasKey $ingress "enabled") }}
        {{ $routes = $localApp.routes }}
      {{- end }}
    {{- end }}
    {{- $foundRatelimitRoutes := false }}
    {{- if $ingress.ratelimit }}
      {{- if $ingress.ratelimit.routes }}
        {{- $routes = $ingress.ratelimit.routes }}
        {{- $foundRatelimitRoutes = true }}
      {{- end }}
    {{- end }}
    {{- if not $foundRatelimitRoutes }}
      {{- if $localApp.ratelimit }}
        {{- if $localApp.ratelimit.routes }}
          {{- $routes = $localApp.ratelimit.routes }}
        {{- end }}
      {{- end }}
    {{- end }}
    {{- $additionalRoutes := $ingress.additionalRoutes }}
    {{- if $additionalRoutes }}
      {{- if $routes }}
        {{- $routes = concat $additionalRoutes $routes }}
      {{- else }}
        {{- $routes = $additionalRoutes }}
      {{- end }}
    {{- end }}
  {{- end }}

  {{- range $routes }}
    {{- $rt := .ratelimit }}
    {{- $hasRatelimit = or $hasRatelimit (ternary $rt.enabled ($rt | default false) (hasKey $rt "enabled")) }}
  {{- end }}
  {{- if and  $ratelimitEnabled $hasRatelimit }}

ratelimit_config.yaml: |
  domain: {{ $ratelimit.domain | default $appName }}
  {{- include "titan-mesh-helm-lib-chart.ratelimit.descriptors" (dict "ingress" $ingress "clusters" $clusters "routes" $routes) | nindent 0 }}
  {{- end }}
{{- end }}