{{- define "titan-mesh-helm-lib-chart.configs.ratelimit" }}
  {{- $global := $.Values.global -}}
  {{- $titanSideCars := mergeOverwrite (deepCopy ($global.titanSideCars | default dict)) ($.Values.titanSideCars | default dict) -}}
  {{- $appName := include "titan-mesh-helm-lib-chart.app-name" . -}}
  {{- $ingress := $titanSideCars.ingress }}
ratelimit_config.yaml: |
  domain: {{ $appName }}
  {{- include "titan-mesh-helm-lib-chart.ratelimit.descriptors" (dict "ingress" $ingress) | nindent 0 }}
{{- end }}