{{- define "titan-mesh-helm-lib-chart.configs.ratelimit" }}
  {{- $global := $.Values.global -}}
  {{- $titanSideCars := mergeOverwrite (deepCopy ($global.titanSideCars | default dict)) ($.Values.titanSideCars | default dict) -}}
  {{- $ratelimitEnabled := eq (include "static.titan-mesh-helm-lib-chart.ratelimitEnabled" $titanSideCars) "true" -}}
  {{- $appName := include "titan-mesh-helm-lib-chart.app-name" . -}}
  {{- $ingress := $titanSideCars.ingress }}
  {{- $envoy := $titanSideCars.envoy }}
  {{- $ratelimit := $envoy.ratelimit }}
  {{- $clusters := $envoy.clusters }}
  {{- $hasRatelimit := false }}
  {{- $routes := $ingress.routes | default list }}
  {{- $additionalRoutes := $ingress.additionalRoutes }}
  {{- if $additionalRoutes }}
    {{- if $routes }}
      {{- $routes = concat $additionalRoutes $routes }}
    {{- else }}
      {{- $routes = $additionalRoutes }}
    {{- end }}
  {{- end }}
  {{- range $routes }}
    {{- $rt := .ratelimit }}
    {{- $hasRatelimit = or $hasRatelimit (ternary $rt.enabled ($rt | default false) (hasKey $rt "enabled")) }}
  {{- end }}
  {{- if and $ratelimitEnabled $hasRatelimit }}
ratelimit_config.yaml: |
  domain: {{ $ratelimit.domain | default $appName }}
  {{- include "titan-mesh-helm-lib-chart.ratelimit.descriptors" (dict "ingress" $ingress "clusters" $clusters "routes" $routes) | nindent 0 }}
  {{- end }}
{{- end }}