### instruction on how to get fips version of envoy
### Step 1; run fips version of envoy image into docker container
###         docker run --rm -it --entrypoint bash  gcr.io/istio-enterprise/proxyv2:1.10.2-fips
### Step 2: Use different terminal to perform copy envoy to local host with following commands
### run "docker ps" to get running envoy container ID
### run "docker cp {container ID}:/usr/local/bin/envoy bin/linux-amd64/envoy"
### run "chmod a+x bin/linux-amd64/envoy" to ensure excutable permission
### Step 3: Build docker image with this Dockerfile
FROM sbo-saas-docker-release-local.artifactory-lvn.broadcom.net/broadcom-images/approved/redhat/ubi-minimal:8 
COPY bin/linux-amd64/envoy /usr/local/bin/
