### source from https://console.cloud.google.com/gcr/images/istio-enterprise/GLOBAL/proxyv2
### docker run --rm -it --entrypoint bash  gcr.io/istio-enterprise/proxyv2:1.10.2-fips
### envoy --version
### envoy  version: 748e69252be91d96e3236053541ead5096861594/1.18.3/Clean/RELEASE/BoringSSL-FIPS
FROM gcr.io/istio-enterprise/proxyv2:1.10.2-fips

RUN apt-get update -y && apt-get install -y wget curl --no-install-recommends && rm -rf /var/cache/apt/*


