resources:
  - name: local-myapp
    "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
    type:   STRICT_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: LEAST_REQUEST
    
    connect_timeout: 0.25s
    common_lb_config:
      healthy_panic_threshold:
        value: 25
    outlier_detection:
      enforcing_consecutive_5xx: 0
      enforcing_success_rate: 0
      enforcing_consecutive_gateway_failure: 0
      enforcing_failure_percentage: 0
    circuit_breakers:
      thresholds:
      - priority: "DEFAULT"
        track_remaining: true
        retry_budget:
          budget_percent:
            value: 20.0
          min_retry_concurrency: 3
    health_checks:
    - http_health_check:
        path: /id_epmp_i/health
      interval: 1s
      timeout: 1s
      healthy_threshold: 1
      unhealthy_threshold: 1
      no_traffic_interval: 3s
    load_assignment:
      cluster_name: local-myapp
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: myapp 
                port_value: 8080
    
  - name: ratelimit
    "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
    type: STATIC
    dns_lookup_family: V4_ONLY
    lb_policy: LEAST_REQUEST      
    connect_timeout: 1s
    protocol_selection: USE_CONFIGURED_PROTOCOL
    http2_protocol_options: {}
    circuit_breakers:
      thresholds:
      - priority: "DEFAULT"
        max_requests: 409600
        max_pending_requests: 204800
        retry_budget:
          budget_percent:
            value: 20.0
          min_retry_concurrency: 3
    load_assignment:
      cluster_name: ratelimit
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: ratelimit
                port_value: 8081

