resources:
- "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
  name: tls_sds
  tls_certificate:
    certificate_chain:
      filename: "/secrets/tls.crt"
    private_key:
      filename: "/secrets/tls.key"

