{{- define "titan-mesh-helm-lib-chart.envoy.filter.routes" }}
  {{- $titanSideCars := .titanSideCars }}
  {{- $appName := .appName -}}
  {{- $direction := .direction -}}
  {{- $validation := $titanSideCars.validation }}
  {{- $validationEnabled := false }}
  {{- if $validation }}
    {{- $validationEnabled = ternary $validation.enabled true (hasKey $validation "enabled") }}
  {{- end }}
  {{- $canary := $titanSideCars.canary -}}
  {{- $canaryEnabled := ternary $canary.enabled false (hasKey $canary "enabled") -}}
  {{- $canaryHeaderName := $canary.headerName | default "x-epmp-routing-hint" -}}
  {{- $canaryHeaderValue := $canary.headerValue | default "canary" -}}
  {{- $ingress := $titanSideCars.ingress }}
  {{- $egress := $titanSideCars.egress }}
  {{- $envoy := $titanSideCars.envoy }}
  {{- $clusters := $envoy.clusters }}
  {{- $weightedClusters := $envoy.weightedClusters }}
  {{- $canaryClusters := $envoy.canaryClusters }}
  {{- $remoteMyApp := index $clusters "remote-myapp" }}
  {{- $localMyApp := index $clusters "local-myapp" }}
  {{- $gatewayEnable := false }}
  {{- $defaultBackend := "local-myapp" }}
  {{- if $localMyApp.gateway  -}}
    {{- $gatewayEnable = ternary $localMyApp.gateway.enabled true (hasKey $localMyApp.gateway "enabled") -}}
    {{- if $gatewayEnable -}}
      {{- $defaultBackend = ternary $localMyApp.gateway.defaultBackend "" (hasKey $localMyApp.gateway "defaultBackend") -}}
    {{- end -}}
  {{- end }}
  {{- $routesBuilder := dict "weightedClustersRoutes" (dict) -}}
  {{- $routes := list }}
  {{- $weightedClustersRoutes := $routesBuilder.weightedClustersRoutes -}}
  {{- if $gatewayEnable -}}
    {{- $requestRoutes := ternary $ingress.routes $egress.routes (eq $direction "ingress") | default list -}}
    {{- $additionalRoutes := ternary $ingress.additionalRoutes $egress.additionalRoutes (eq $direction "ingress") | default list }}
    {{- range $additionalRoutes -}}
      {{- $_ := set . "priority" true -}}
    {{- end -}}
    {{- $requestRoutes = concat $additionalRoutes $requestRoutes  -}}
    {{- range $requestRoutes -}}
      {{- $match := .match -}}
      {{- $route := .route -}}
      {{- $priority := .priority | default false -}}
      {{- if and (hasKey . "route") (hasKey $route "cluster") -}}
        {{- $clusterName := $route.cluster -}}
        {{- $clusterValue := get $clusters $clusterName -}}
        {{- $requestOverride := dict -}}
        {{- if $match -}}
          {{- $_ := set $requestOverride "match" $match -}}
        {{- end -}}
        {{- $routeActions := dict -}}
        {{- if $route -}}
          {{- range $k, $v := $route -}}
            {{- if ne $k "cluster" -}}
              {{- $_ := set $routeActions $k $v -}}
            {{- end -}}
          {{- end -}}
        {{- end -}}
        {{- if $clusterValue -}}
          {{- $clusterCanaryNamespace := "" -}}
          {{- $clusterCanarySupport := false -}}
          {{- if $routeActions -}}
            {{- $_ := set $requestOverride "route" $routeActions -}}
          {{- end -}}
          {{- include "titan-mesh-helm-lib-chart.envoy.filter.routes.prepare" (dict "routesBuilder" $routesBuilder "canaryHeaderValue" $canaryHeaderValue "canaryHeaderName" $canaryHeaderName "clusterCanaryNamespace" $clusterCanaryNamespace "clusterCanarySupport" $clusterCanarySupport "clusterName" $clusterName "clusterValue" $clusterValue "requestOverride" $requestOverride) }}
          {{- if hasKey $routesBuilder "routes" -}}
            {{- $buiderRoutes := $routesBuilder.routes -}}
            {{- range $buiderRoutes }}
              {{- $newRoute := . | deepCopy -}}
              {{- if $priority -}}
                {{- $_ := set $newRoute "priority" $priority -}}
              {{- end -}}
              {{- $routes = append $routes $newRoute -}}
            {{- end }}
          {{- end -}}
        {{- else if hasKey $weightedClusters $clusterName -}}
          {{- $wsv := get $weightedClusters $clusterName -}}
          {{- range $clusterName, $weight := $wsv -}}
            {{- $clusterValue = get $clusters $clusterName -}}
            {{- if $clusterValue -}}
              {{- $clusterCanaryNamespace := "" -}}
              {{- $clusterCanarySupport := false -}}
              {{- if $routeActions -}}
                {{- $_ := set $requestOverride "route" $routeActions -}}
              {{- end -}}
              {{- include "titan-mesh-helm-lib-chart.envoy.filter.routes.prepare" (dict "routesBuilder" $routesBuilder "canaryHeaderValue" $canaryHeaderValue "canaryHeaderName" $canaryHeaderName "clusterCanaryNamespace" $clusterCanaryNamespace "clusterCanarySupport" $clusterCanarySupport "clusterName" $clusterName "clusterValue" $clusterValue "requestOverride" $requestOverride) }}
              {{- if hasKey $routesBuilder "routes" -}}
                {{- $buiderRoutes := $routesBuilder.routes -}}
                {{- range $buiderRoutes }}
                  {{- $newRoute := . | deepCopy -}}
                  {{- if $priority -}}
                    {{- $_ := set $newRoute "priority" $priority -}}
                  {{- end -}}
                  {{- $routes = append $routes $newRoute -}}
                {{- end }}
              {{- end -}}
            {{- end -}}
          {{- end -}}
        {{- else if hasKey $canaryClusters $clusterName -}}
          {{- $canaryCluster := get $canaryClusters $clusterName -}}
          {{- if $canaryCluster -}}
            {{- $clusterCanaryNamespace := $canaryCluster.canaryNamespace -}}
            {{- if $routeActions -}}
              {{- $_ := set $requestOverride "route" $routeActions -}}
            {{- end -}}
            {{- $canaryClusterName := printf "%s.%s" $clusterName $canaryCluster.namespace -}}
            {{- $clusterValue := get $clusters $canaryClusterName -}}
            {{- include "titan-mesh-helm-lib-chart.envoy.filter.routes.prepare" (dict "routesBuilder" $routesBuilder "canaryHeaderValue" $canaryHeaderValue "canaryHeaderName" $canaryHeaderName "clusterCanaryNamespace" $clusterCanaryNamespace "clusterCanarySupport" true "clusterName" $canaryClusterName "clusterValue" $clusterValue "requestOverride" $requestOverride) }}
            {{- if hasKey $routesBuilder "routes" -}}
              {{- $buiderRoutes := $routesBuilder.routes -}}
              {{- range $buiderRoutes }}
                {{- $newRoute := . | deepCopy -}}
                {{- if $priority -}}
                  {{- $_ := set $newRoute "priority" $priority -}}
                {{- end -}}
                {{- $routes = append $routes $newRoute -}}
              {{- end }}
            {{- end -}}
          {{- end -}}
        {{- end -}}
      {{- else -}}
        {{- $routes = append $routes . -}}
      {{- end -}}
    {{- end -}}
    {{- range $cn, $cv := $clusters }}
      {{- if and (ne $cn "local-myapp") (ne $cn "remote-myapp") }}
        {{- $external := $cv.external | default false -}}
        {{- $includeIt := ternary false (ternary false true $external) (eq $direction "egress") }}
        {{- $clusterCanaryNamespace := $cv.canaryNamespace | default "" -}}
        {{- $clusterCanarySupport := ternary (and $cv.supportCanary (ne $clusterCanaryNamespace "")) ((ne $clusterCanaryNamespace "") | default $canaryEnabled) (hasKey $cv "supportCanary") -}}
        {{- if $includeIt }}
          {{- $_ := unset $routesBuilder "routes" -}}
          {{- include "titan-mesh-helm-lib-chart.envoy.filter.routes.prepare" (dict "routesBuilder" $routesBuilder "canaryHeaderValue" $canaryHeaderValue "canaryHeaderName" $canaryHeaderName "clusterCanaryNamespace" $clusterCanaryNamespace "clusterCanarySupport" $clusterCanarySupport "clusterName" $cn "clusterValue" $cv) }}
          {{- if hasKey $routesBuilder "routes" -}}
            {{- $buiderRoutes := $routesBuilder.routes -}}
            {{- range $buiderRoutes }}
              {{- $newRoute := . | deepCopy -}}
              {{- $routes = append $routes $newRoute -}}
            {{- end }}
          {{- end -}}
        {{- end }}
      {{- end }}
    {{- end }}
    {{- range $weightedClusterId, $weightClusterRoutesValue := $weightedClustersRoutes }}
      {{- if hasSuffix "-canary" $weightedClusterId }}
        {{- $weightedRoutes := $weightClusterRoutesValue.routes }}
        {{- $weightedClusters := $weightClusterRoutesValue.weightedClusters }}
        {{- range $weightedRoutes }}        
          {{- $_ := set . "route" (dict "weightedClusters" $weightedClusters) }}
          {{- $routes = append $routes . }}
        {{- end }}
      {{- end }}
    {{- end }}
    {{- range $weightedClusterId, $weightClusterRoutesValue := $weightedClustersRoutes }}
      {{- if not (hasSuffix "-canary" $weightedClusterId) }}
        {{- $weightedRoutes := $weightClusterRoutesValue.routes }}
        {{- $weightedClusters := $weightClusterRoutesValue.weightedClusters }}
        {{- range $weightedRoutes }}        
          {{- $_ := set . "route" (dict "weightedClusters" $weightedClusters) }}
          {{- $routes = append $routes . }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- else }}
    {{- $routes = ternary $ingress.routes $egress.routes (eq "ingress" $direction) | default list }}
    {{- $additionalRoutes := ternary $ingress.additionalRoutes $egress.additionalRoutes (eq "ingress" $direction) | default list }}
    {{- $routes = concat $additionalRoutes $routes }}
  {{- end }}

  {{- include "titan-mesh-helm-lib-chart.envoy.filter.request.routes" (dict "routes" $routes "direction" $direction "clusters" $clusters "remoteMyApp" $remoteMyApp "envoy" $envoy "validationEnabled" $validationEnabled "gatewayEnable" $gatewayEnable) }}
  {{- if eq $direction "ingress" }}
    {{- $cluster := index $envoy.clusters "local-myapp" }}
    {{- $retryPolicy := $cluster.retryPolicy }}
                - match:
                    prefix: /
    {{- if eq $defaultBackend "" }}
                  direct_response:
                    status: {{ $cluster.directResponseCode | default "404" }}
                    body:
                      inline_string: {{ ($cluster.directResponseMessage | default (printf "%s:No matching route" $appName)) | squote }}
    {{- else }}
                  route:
            {{- if $cluster.addRequestHeaders }}
                    request_headers_to_add:
              {{- range $cluster.addRequestHeaders }}
                    - header:
                        key: {{ .name }}
                  {{- if .value }}
                        value: {{ .value }}
                  {{- else if .rawValue }}
                        raw_value: {{ .rawValue }}
                  {{- end }}
                      append_action: {{ .appendAction | default "ADD_IF_ABSENT" }}
                      keep_empty_value: {{ .keepEmptyValue | default "false" }}
              {{- end }}
            {{- end }}
            {{- if $cluster.removeRequestHeaders }}
                    request_headers_to_remove:
              {{- range $cluster.removeRequestHeaders }}
                    - {{ . }}
              {{- end }}
            {{- end }}
            {{- if $cluster.addResponseHeaders }}
                    response_headers_to_add:
              {{- range $cluster.addResponseHeaders }}
                    - header:
                        key: {{ .name }}
                  {{- if .value }}
                        value: {{ .value }}
                  {{- else if .rawValue }}
                        raw_value: {{ .rawValue }}
                  {{- end }}
                      append_action: {{ .appendAction | default "ADD_IF_ABSENT" }}
                      keep_empty_value: {{ .keepEmptyValue | default "false" }}
              {{- end }}
            {{- end }}
            {{- if $cluster.removeResponseHeaders }}
                    response_headers_to_remove:
              {{- range $cluster.removeResponseHeaders }}
                    - {{ . }}
              {{- end }}
            {{- end }}
                    cluster: {{ $defaultBackend }}
                    retry_policy:
                      num_retries: {{ coalesce $retryPolicy.numRetries "1" }}
                      retry_on: {{ coalesce $retryPolicy.retryOn "reset,connect-failure,refused-stream,retriable-status-codes" }}
          {{- if $retryPolicy.retriableStatusCode }}
                      retriable_status_codes: 
              {{- range $retryPolicy.retriableStatusCode }}
                        - {{ . }}
              {{- end }}
          {{- end }}
          {{- if $retryPolicy.hostSelectionRetryMaxAttempts }}
                      host_selection_retry_max_attempts: {{ $retryPolicy.hostSelectionRetryMaxAttempts }}
          {{- end }}
                    timeout: {{ coalesce $cluster.timeout "15s" }}
      {{- if $cluster.idleTimeout }}
                    idle_timeout: {{ $cluster.idleTimeout }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
