{{- define "titan-mesh-helm-lib-chart.envoy.filter.routes" }}
  {{- $titanSideCars := .titanSideCars }}
  {{- $appName := .appName -}}
  {{- $direction := .direction -}}
  {{- $validation := $titanSideCars.validation }}
  {{- $routingType := .routingType -}}
  {{- $validationEnabled := false }}
  {{- if $validation }}
    {{- $validationEnabled = ternary $validation.enabled true (hasKey $validation "enabled") }}
  {{- end }}
  {{- $canary := $titanSideCars.canary -}}
  {{- $canaryHeaderName := $canary.headerName | default "x-epmp-routing-hint" -}}
  {{- $canaryHeaderValue := $canary.headerValue | default "canary" -}}
  {{- $ingress := $titanSideCars.ingress }}
  {{- $egress := $titanSideCars.egress }}
  {{- $envoy := $titanSideCars.envoy }}
  {{- $clusters := $envoy.clusters }}
  {{- $weightedClusters := $envoy.weightedClusters -}}
  {{- $remoteMyApp := index $clusters "remote-myapp" }}
  {{- $localMyApp := index $clusters "local-myapp" }}
  {{- $gatewayEnable := false }}
  {{- $defaultBackend := "local-myapp" }}
  {{- if $localMyApp.gateway  -}}
    {{- $gatewayEnable = ternary $localMyApp.gateway.enabled true (hasKey $localMyApp.gateway "enabled") -}}
    {{- if $gatewayEnable -}}
      {{- $defaultBackend = ternary $localMyApp.gateway.defaultBackend "" (hasKey $localMyApp.gateway "defaultBackend") -}}
    {{- end -}}
  {{- end }}
  {{- $routesBuilder := dict "routes" (list) "weightedClustersRoutes" (dict) -}}
  {{- $routes := $routesBuilder.routes }}
  {{- $weightedClustersRoutes := $routesBuilder.weightedClustersRoutes -}}
  {{- if $gatewayEnable -}}
    {{- $requestRoutes := ternary $ingress.routes $egress.routes (eq $direction "ingress") -}}
    {{- range $requestRoutes -}}
      {{- $match := .match -}}
      {{- $route := .route -}}
      {{- if hasKey $route "cluster" -}}
        {{- $clusterName := $route.cluster -}}
        {{- $clusterValue := get $clusters $clusterName -}}
        {{- $requestOverride := dict -}}
        {{- if $match -}}
          {{- $_ := set $requestOverride "match" $match -}}
        {{- end -}}
        {{- $routeActions := dict -}}
        {{- if $route -}}
          {{- range $k, $v := $route -}}
            {{- if ne $k "cluster" -}}
              {{- $_ := set $routeActions $k $v -}}
            {{- end -}}
          {{- end -}}
        {{- end -}}
        {{- if $clusterValue -}}
          {{- $clusterCanaryNamespace := $clusterValue.canaryNamespace | default "" -}}
          {{- $clusterCanarySupport := $clusterValue.supportCanary | default true -}}
          {{- if $routeActions -}}
            {{- $_ := set $requestOverride "route" $routeActions -}}
          {{- end -}}
          {{- include "titan-mesh-helm-lib-chart.envoy.filter.routes.prepare" (dict "routesBuilder" $routesBuilder "canaryHeaderValue" $canaryHeaderValue "canaryHeaderName" $canaryHeaderName "clusterCanaryNamespace" $clusterCanaryNamespace "clusterCanarySupport" $clusterCanarySupport "clusterName" $clusterName "clusterValue" $clusterValue "requestOverride" $requestOverride) }}         
        {{- else if hasKey $weightedClusters $clusterName -}}
          {{- $wsv := get $weightedClusters $clusterName -}}
          {{- range $clusterName, $weight := $wsv -}}
            {{- $clusterValue = get $clusters $clusterName -}}
            {{- if $clusterValue -}}
              {{- $clusterCanaryNamespace := $clusterValue.canaryNamespace | default "" -}}
              {{- $clusterCanarySupport := $clusterValue.supportCanary | default true -}}
              {{- if $routeActions -}}
                {{- $_ := set $requestOverride "route" $routeActions -}}
              {{- end -}}
              {{- include "titan-mesh-helm-lib-chart.envoy.filter.routes.prepare" (dict "routesBuilder" $routesBuilder "canaryHeaderValue" $canaryHeaderValue "canaryHeaderName" $canaryHeaderName "clusterCanaryNamespace" $clusterCanaryNamespace "clusterCanarySupport" $clusterCanarySupport "clusterName" $clusterName "clusterValue" $clusterValue "requestOverride" $requestOverride) }}
            {{- end -}}
          {{- end -}}
        {{- end -}}
      {{- end -}}
    {{- end -}}
    {{- range $cn, $cv := $clusters }}
      {{- if and (ne $cn "local-myapp") (ne $cn "remote-myapp") }}
        {{- $includeIt := ternary false true (eq $direction "egress") }}
        {{- $clusterCanaryNamespace := $cv.canaryNamespace | default "" -}}
        {{- $clusterCanarySupport := $cv.supportCanary | default true -}}
        {{- if eq $clusterCanaryNamespace "" -}}
          {{- $clusterCanarySupport = false -}}
        {{- end -}}
        {{- if $includeIt }}
          {{- include "titan-mesh-helm-lib-chart.envoy.filter.routes.prepare" (dict "routesBuilder" $routesBuilder "canaryHeaderValue" $canaryHeaderValue "canaryHeaderName" $canaryHeaderName "clusterCanaryNamespace" $clusterCanaryNamespace "clusterCanarySupport" $clusterCanarySupport "clusterName" $cn "clusterValue" $cv) }}
          {{- range $cv.routes }}
            {{- $route := .route | default dict -}}
            {{- $_ := set $route "cluster" $cn -}}
            {{- if hasKey $cv "fixedSiteDomainName" -}}
              {{- $match := .match | deepCopy }}
              {{- $headers := $match.headers | default list -}}
              {{- $addFixedSiteRoute := true -}}
              {{- range $headers -}}
                {{- if and (eq .key ":authority") (hasKey . "eq") -}}
                  {{- if not (contains $cv.fixedSiteDomainName .eq) -}}
                    {{- $addFixedSiteRoute = false -}}
                  {{- end -}}
                {{- end }}
              {{- end -}}
              {{- if $addFixedSiteRoute -}}
                {{- $headers = append $headers (dict "key" ":authority" "ew" $cv.fixedSiteDomainName) }}
                {{- if $clusterCanarySupport }}
                  {{- $canaryHeaders := $headers | deepCopy -}}
                  {{- $canaryMatch := $match | deepCopy -}}
                  {{- $canaryRoute := $route | deepCopy -}}
                  {{- $_ := set $canaryRoute "cluster" (printf "%s.%s" ($cv.alias | default $cn) $clusterCanaryNamespace) -}}
                  {{- $_ := set $canaryRoute "baseCluster" $cn -}}
                  {{- $canaryHeaders = append $canaryHeaders (dict "key" $canaryHeaderName "eq" $canaryHeaderValue) -}}
                  {{- $_ := set $canaryMatch "headers" $canaryHeaders -}}
                  {{- $routes = append $routes (dict "match" $canaryMatch "route" $canaryRoute "ratelimit" .ratelimit) }}
                {{- end }}
                {{- $_ := set $match "headers" $headers }}
                {{- $routes = append $routes (dict "match" $match "route" $route "ratelimit" .ratelimit) }}
              {{- end -}}
            {{- else if not (hasKey $cv "weightedClusterId") }}
              {{- $match := .match }}
              {{- $headers := $match.headers | default list -}}
              {{- if $clusterCanarySupport }}
                {{- $canaryHeaders := $headers | deepCopy -}}
                {{- $canaryMatch := $match | deepCopy -}}
                {{- $canaryRoute := $route | deepCopy -}}
                {{- $_ := set $canaryRoute "cluster" (printf "%s.%s" ($cv.alias | default $cn) $clusterCanaryNamespace) -}}
                {{- $_ := set $canaryRoute "baseCluster" $cn -}}
                {{- $canaryHeaders = append $canaryHeaders (dict "key" $canaryHeaderName "eq" $canaryHeaderValue) -}}
                {{- $_ := set $canaryMatch "headers" $canaryHeaders -}}
                {{- $routes = append $routes (dict "match" $canaryMatch "route" $canaryRoute "ratelimit" .ratelimit) }}
              {{- end }}
              {{- $routes = append $routes (dict "match" $match "route" $route "ratelimit" .ratelimit) }}
            {{- end }}
          {{- end }}
          {{- if hasKey $cv "weightedClusterId" }}
            {{- if hasKey $weightedClustersRoutes $cv.weightedClusterId -}}
              {{- if $clusterCanarySupport }}
                {{- $wr := get $weightedClustersRoutes (printf "%s-canary" $cv.weightedClusterId) }}
                {{- $wrList := $wr.weightedClusters }}
                {{- $wrList = append $wrList (dict "name" (printf "%s.%s" ($cv.alias | default $cn) $clusterCanaryNamespace) "weight" $cv.weight) }}
                {{- $_ := set $wr "weightedClusters" $wrList }}
                {{- $_ := set $weightedClustersRoutes (printf "%s-canary" $cv.weightedClusterId) $wr }}
              {{- end }}
              {{- $wr := get $weightedClustersRoutes $cv.weightedClusterId }}
              {{- $wrList := $wr.weightedClusters }}
              {{- $wrList = append $wrList (dict "name" $cn "weight" $cv.weight) }}
              {{- $_ := set $wr "weightedClusters" $wrList }}
              {{- $_ := set $weightedClustersRoutes $cv.weightedClusterId $wr }}
            {{- else }}
              {{- if $clusterCanarySupport }}
                {{- $canaryRoutes := $cv.routes | deepCopy -}}
                {{- range $canaryRoutes -}}
                  {{- $match := .match -}}
                  {{- $headers := $match.headers | default list -}}
                  {{- $headers = append $headers (dict "key" $canaryHeaderName "eq" $canaryHeaderValue) -}}
                  {{- $_ := set $match "headers" $headers -}}
                {{- end -}}
                {{- $_ := set $weightedClustersRoutes (printf "%s-canary" $cv.weightedClusterId) (dict "routes" $canaryRoutes "weightedClusters" (list (dict "name" (printf "%s.%s" ($cv.alias | default $cn) $clusterCanaryNamespace) "weight" $cv.weight))) }}
              {{- end }}
              {{- $_ := set $weightedClustersRoutes $cv.weightedClusterId (dict "routes" $cv.routes "weightedClusters" (list (dict "name" $cn "weight" $cv.weight))) }}
            {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
    {{- range $weightedClusterId, $weightClusterRoutesValue := $weightedClustersRoutes }}
      {{- if hasSuffix "-canary" $weightedClusterId }}
        {{- $weightedRoutes := $weightClusterRoutesValue.routes }}
        {{- $weightedClusters := $weightClusterRoutesValue.weightedClusters }}
        {{- range $weightedRoutes }}        
          {{- $_ := set . "route" (dict "weightedClusters" $weightedClusters) }}
          {{- $routes = append $routes . }}
        {{- end }}
      {{- end }}
    {{- end }}
    {{- range $weightedClusterId, $weightClusterRoutesValue := $weightedClustersRoutes }}
      {{- if not (hasSuffix "-canary" $weightedClusterId) }}
        {{- $weightedRoutes := $weightClusterRoutesValue.routes }}
        {{- $weightedClusters := $weightClusterRoutesValue.weightedClusters }}
        {{- range $weightedRoutes }}        
          {{- $_ := set . "route" (dict "weightedClusters" $weightedClusters) }}
          {{- $routes = append $routes . }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- else }}
    {{- $routes = ternary $ingress.routes $egress.routes (eq "ingress" $direction) }}
    {{- $additionalRoutes := ternary $ingress.additionalRoutes $egress.additionalRoutes (eq "ingress" $direction) }}
    {{- if and $additionalRoutes }}
      {{- if $routes }}
        {{- $routes = concat $additionalRoutes $routes }}
      {{- else }}
        {{- $routes = $additionalRoutes }}
      {{- end }}
    {{- end }} 
  {{- end }}
  {{- include "titan-mesh-helm-lib-chart.envoy.filter.request.routes" (dict "routes" $routes "direction" $direction "clusters" $clusters "remoteMyApp" $remoteMyApp "routingType" $routingType "envoy" $envoy "validationEnabled" $validationEnabled "gatewayEnable" $gatewayEnable) }}
  {{- if and (eq $direction "ingress") (eq $routingType "pathBasedRouting") }}
    {{- $gatewayIngressRoutes := $ingress.routes -}}
    {{- if and $gatewayEnable $gatewayIngressRoutes }}
      {{- include "titan-mesh-helm-lib-chart.envoy.filter.request.routes" (dict "routes" $gatewayIngressRoutes "direction" $direction "clusters" $clusters "remoteMyApp" $remoteMyApp "routingType" $routingType "envoy" $envoy "validationEnabled" $validationEnabled "gatewayEnable" $gatewayEnable) }}
    {{- end }}
    {{- $cluster := index $envoy.clusters "local-myapp" }}
    {{- $retryPolicy := $cluster.retryPolicy }}
                - match:
                    prefix: /
    {{- if eq $defaultBackend "" }}
                  direct_response:
                    status: {{ $cluster.directResponseCode | default "404" }}
                    body:
                      inline_string: {{ ($cluster.directResponseMessage | default (printf "%s:No matching route" $appName)) | squote }}
    {{- else }}
                  route:
            {{- if $cluster.addRequestHeaders }}
                    request_headers_to_add:
              {{- range $cluster.addRequestHeaders }}
                    - header:
                        key: {{ .name }}
                  {{- if .value }}
                        value: {{ .value }}
                  {{- else if .rawValue }}
                        raw_value: {{ .rawValue }}
                  {{- end }}
                      append_action: {{ .appendAction | default "ADD_IF_ABSENT" }}
                      keep_empty_value: {{ .keepEmptyValue | default "false" }}
              {{- end }}
            {{- end }}
            {{- if $cluster.removeRequestHeaders }}
                    request_headers_to_remove:
              {{- range $cluster.removeRequestHeaders }}
                    - {{ . }}
              {{- end }}
            {{- end }}
            {{- if $cluster.addResponseHeaders }}
                    response_headers_to_add:
              {{- range $cluster.addResponseHeaders }}
                    - header:
                        key: {{ .name }}
                  {{- if .value }}
                        value: {{ .value }}
                  {{- else if .rawValue }}
                        raw_value: {{ .rawValue }}
                  {{- end }}
                      append_action: {{ .appendAction | default "ADD_IF_ABSENT" }}
                      keep_empty_value: {{ .keepEmptyValue | default "false" }}
              {{- end }}
            {{- end }}
            {{- if $cluster.removeResponseHeaders }}
                    response_headers_to_remove:
              {{- range $cluster.removeResponseHeaders }}
                    - {{ . }}
              {{- end }}
            {{- end }}
                    cluster: {{ $defaultBackend }}
                    retry_policy:
                      num_retries: {{ coalesce $retryPolicy.numRetries "1" }}
                      retry_on: {{ coalesce $retryPolicy.retryOn "reset,connect-failure,refused-stream,retriable-status-codes" }}
          {{- if $retryPolicy.retriableStatusCode }}
                      retriable_status_codes: 
              {{- range $retryPolicy.retriableStatusCode }}
                        - {{ . }}
              {{- end }}
          {{- end }}
          {{- if $retryPolicy.hostSelectionRetryMaxAttempts }}
                      host_selection_retry_max_attempts: {{ $retryPolicy.hostSelectionRetryMaxAttempts }}
          {{- end }}
                    timeout: {{ coalesce $cluster.timeout "15s" }}
      {{- if $cluster.idleTimeout }}
                    idle_timeout: {{ $cluster.idleTimeout }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
